export const SELECT_PRODUCT ='SELECT_PRODUCT';
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT';
export const INCREMENT_PRODUCT_COUNT = 'INCREMENT_PRODUCT_COUNT';
export const DECREMENT_PRODUCT_COUNT = 'DECREMENT_PRODUCT_COUNT';